# Generated by Django 5.2.6 on 2025-09-30 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
        ('produits', '0003_alter_produit_quantite_stock_alter_produit_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='client_fournisseur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='quantite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('impayee', 'Impayée'), ('partielle', 'Payée Partiellement'), ('payee', 'Payée')], default='impayee', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
