# Generated by Django 5.2.6 on 2025-09-26 11:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_produite', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('produit_fini', models.ForeignKey(limit_choices_to={'type': 'PF'}, on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='sites.sitefabrication')),
            ],
        ),
        migrations.CreateModel(
            name='ConsommationMatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('produit_mp', models.ForeignKey(limit_choices_to={'type': 'MP'}, on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='production.production')),
            ],
        ),
    ]
