# Generated by Django 5.2.6 on 2025-09-26 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('produits', '0003_alter_produit_quantite_stock_alter_produit_unite'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='produits.produit')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='sites.sitefabrication')),
            ],
        ),
    ]
