# Generated by Django 5.2.6 on 2025-09-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
