# Generated by Django 5.2.6 on 2025-09-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_produit_quantite_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='quantite_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantité actuelle en stock', max_digits=12),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(help_text='Ex: kg, litre, unité', max_length=50),
        ),
    ]
